spring.application.name=spring-security-multi-user

spring.datasource.url=jdbc:postgresql://localhost:5432/spring-security-multi-user

spring.datasource.username=postgres
spring.datasource.password=jamshid77
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8085

